#%RAML 1.0
title: Customer Service
version: 1.0
baseUri: https://pruebas.com/version
types:
    Customer: 
        type: !include Schemas/Customer.schema.json
    Customers:
        type: !include Schemas/Customer.schema.json
    Error:
        type: !include Schemas/GenericResponse.schema.json
/order:
    post:
        description: Recurso para la creacion de clientes
        body:
            application/json:
                type : Customer
        responses:
            200:
                body:
                    application/json:
                        type: number
            500:
                body:
                    application/json:
                        type: Error      
    put:
    
        description: Recurso para la actualizacion de clientes
        body:
            application/json:
                type : Customer
        responses:
            200:
                body:
                    application/json:
                        type: boolean
            500:
                body:
                    application/json:
                        type: Error   

    patch:
    
        description: Recurso para la actualizacion de la categoria de un cliente
        queryParameters:
            idCliente:
                type: string
                example: 1010206809
                required:true
            idCategoria:
                type:string
                example: 5
                required:true
        responses:
            200:
                body:
                    application/json:
                        type: boolean 
            500:
                body:
                    application/json:
                        type: Error   
    get:
        description: consultar cliente por el numero de un producto
        queryParameters:
            numeroProducto:
                type:string
                required:true
                example:5
        responses:
            200:
                body:
                    application/json:
                        type: Customers
            500:
                body:
                    application/json:
                        type: Error   
    
    /{id}:
        get:
            description: Recurso para la consulta de una cliente por id
            responses:
                200:
                    body:
                        application/json:
                            type: Customer
                500:
                    body:
                        application/json:
                            type: Error       