#%RAML 1.0
title: MAF Service
version: 1.0
baseUri: https://pruebas.com/version
types:
    MAF: 
        type: !include Schemas/MAF.schema.json
    Error:
        type: !include Schemas/GenericResponse.schema.json


/MAF:
    post:
        description: Recurso para validar tarjetas de credito
        body:
            application/json:
                type : MAF
        responses:
            200:
                body:
                    application/json:
                        type: boolean
            500:
                body:
                    application/json:
                        type: Error      