#%RAML 1.0
title: Order Service
version: 1.0
baseUri: https://pruebas.com/version
types:
    Order: 
        type: !include Schemas/Order.schema.json    
    Orders:
        type: Order[]
    Error:
        type: !include Schemas/GenericResponse.schema.json     

/order:
    post:
        description: Recurso para la creacion de ordenes
        body:
            application/json:
                type : Order
        responses:
            200:
                body:
                    application/json:
                        type: number
            500:
                body:
                    application/json:
                        type: Error

    get:
        description: Consultar por cliente
        queryParameters:
            idCustomer:
                type: integer
                required:true
        responses:
            200:
                body:
                    application/json:
                        type:Order
            500:
                body:
                    application/json:
                        type: Error

    /closedWithHighPrice: 
        get:               
        description: Ordenes cerradas con alta facturacion.
        queryParameters:
            beginDate:
                type:string
                required:true
            endDate:
                type:string
                required:true

        responses:
            200:
                body:
                    application/json:
                        type:Orders
            500:
                body:
                    application/json:
                        type: Error

    /unclosedOrders:                
        get:               
            description: Ordenes que mas tiempo llevan abiertas.
            responses:
                200:
                    body:
                        application/json:
                            type:Orders
                500:
                    body:
                        application/json:
                            type: Error
    
    /totalBilled:      
        get:                 
            description: Total Facturado.
            queryParameters:
                month:
                    type:number
                    required:true
                year:
                    type:number
                    required:true
            responses:
                200:
                    body:
                        application/json:
                            type: number
                500:
                    body:
                        application/json:
                            type: Error

    /byItemQuantity:        
        get:               
            description: Ordenes por numero de items.
            responses:
                200:
                    body:
                        application/json:
                            type:Orders
                500:
                    body:
                        application/json:
                            type: Error
    
    /{id}:
        get:
            description: Recurso para la consulta de una orden por id
            responses:
                200:
                    body:
                        application/json:
                            type:Order
                 500:
                    body:
                        application/json:
                            type: Error                         
        patch:
            description: Cambiar estado de una orden
            responses:
                200:
                    body:
                        application/json:
                            type:boolean
                500:
                    body:
                        application/json:
                            type: Error                          
