#%RAML 1.0
title: "Product Service"
version: "1.0"
baseUri: https://pruebas.com/version
types:
    Product: !include Schemas/Product.schema.json
    Products: !include Schemas/Products.schema.json
    Error: !include Schemas/GenericResponse.schema.json
/product:
        post:
             description: "Recurso para la creacion de productos"
             body:
                  application/json:
                       type: Product
             responses:
                 200:
                     body:
                          application/json:
                               type: boolean
                 500:
                     body:
                          application/json:
                               type: Error
        /{id}:
              get:
                  description: "Recurso para la consulta de un producto por id"
                  responses:
                     200:
                         body:
                             application/json:
                                 type: Product
                     500:
                         body:
                            application/json:
                                 type: Error
        /byCode:
          get:
              description: "Recurso para la consulta de productos por codigo"
              queryParameters:
                   code:
                    type: string
              responses:
                 200:
                    body:
                      application/json:
                         type: Products
                 500:
                    body:
                       application/json:
                           type: Error
        /byCriteria:
          get:
              description: "Recurso para la consulta de productos por nombre o por descripcion"
              queryParameters:
                   criteria:
                    type: string
              responses:
                 200:
                     body:
                          application/json:
                             type: Products
                 500:
                     body:
                         application/json:
                             type: Error
        /topFive:
          get:
              description: "Recurso para la consulta del top 5 de productos"
              responses:
                 200:
                     body:
                          application/json:
                             type: Products
                 500:
                     body:
                         application/json:
                             type: Error
